// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TGHarker.Identity.Abstractions.Models.Generated;

#nullable disable

namespace TGHarker.Identity.Silo.Migrations
{
    [DbContext(typeof(SearchDesignTimeContext))]
    partial class SearchDesignTimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.ClientStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("ClientName")
                        .HasDatabaseName("IX_ClientState_ClientName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ClientState_IsActive");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ClientState_TenantId");

                    b.ToTable("ClientStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.InvitationStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_InvitationState_Email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InvitationState_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_InvitationState_TenantId");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_InvitationState_Token");

                    b.ToTable("InvitationStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.OrganizationInvitationStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_OrganizationInvitationState_Email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_OrganizationInvitationState_OrganizationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OrganizationInvitationState_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_OrganizationInvitationState_TenantId");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_OrganizationInvitationState_Token");

                    b.ToTable("OrganizationInvitationStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.OrganizationMembershipStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_OrganizationMembershipState_IsActive");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_OrganizationMembershipState_OrganizationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_OrganizationMembershipState_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_OrganizationMembershipState_UserId");

                    b.ToTable("OrganizationMembershipStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.OrganizationStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("IX_OrganizationState_Identifier");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_OrganizationState_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_OrganizationState_Name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_OrganizationState_TenantId");

                    b.ToTable("OrganizationStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.TenantMembershipStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TenantMembershipState_IsActive");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_TenantMembershipState_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TenantMembershipState_UserId");

                    b.ToTable("TenantMembershipStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.TenantStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("IX_TenantState_Identifier");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TenantState_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_TenantState_Name");

                    b.ToTable("TenantStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Identity.Abstractions.Models.Generated.UserStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_UserState_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserState_IsActive");

                    b.ToTable("UserStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
